server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/resume?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  freemarker:
    suffix: .ftl
admin:
  username: yangxin
  password: 123456

